version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - winston-loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki
    networks:
      - winston-loki

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: worasalid/winston-loki-nodejs:latest
    container_name: winston-loki-nodejs-container
    ports:
      - "4000:4000"
    networks:
      - winston-loki
    depends_on:
      - loki

networks:
  winston-loki:
    driver: bridge
